import { getBrowserWindow } from '../../legacy/legacyApi.js';

export const cts = {
  tabsBar: { display: 'flex', gap: 4, padding: '0 4px', marginBottom: 12, borderBottom: '1px solid var(--border)', flexWrap: 'wrap', alignItems: 'center' },
  tabBtn: { padding: '10px 16px', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'var(--font)', fontSize: 13, color: 'var(--text2)', borderBottom: '2px solid transparent', whiteSpace: 'nowrap' },
  tabBtnActive: { color: 'var(--accent)', borderBottomColor: 'var(--accent)', fontWeight: 600 },
  tabsDivider: { width: 1, height: 22, background: 'var(--border)', margin: '0 8px' },
  fallback: { padding: 40, textAlign: 'center', color: 'var(--text2)', fontSize: 13 },
  root: { display: 'grid', gridTemplateColumns: '280px 1fr', gap: 16, height: 'calc(100vh - 160px)', minHeight: 600 },
  leftCol: { display: 'flex', flexDirection: 'column', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden' },
  leftHeader: { padding: 12, borderBottom: '1px solid var(--border)', display: 'flex', flexDirection: 'column', gap: 8 },
  newBtn: { padding: '9px 14px', background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
  search: { padding: '8px 12px', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', outline: 'none' },
  leftList: { flex: 1, overflowY: 'auto' },
  recetteItem: { padding: '11px 14px', borderBottom: '1px solid var(--border)', cursor: 'pointer', transition: 'background .12s' },
  recetteItemActive: { background: 'var(--accent-light)', borderLeft: '3px solid var(--accent)' },
  // ─── Hiérarchie plats ───
  platHeader: { display: 'flex', alignItems: 'center', gap: 4, padding: '8px 8px 8px 6px', borderBottom: '1px solid var(--border)' },
  platToggle: { width: 22, height: 22, padding: 0, background: 'none', border: 'none', cursor: 'pointer', fontSize: 10, color: 'var(--text2)', flexShrink: 0 },
  platName: { fontSize: 13, fontWeight: 700, color: 'var(--text)', fontFamily: 'var(--font-serif)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  platMeta: { fontSize: 10, color: 'var(--text2)', marginTop: 2 },
  platEditBtn: { width: 24, height: 24, background: 'none', border: 'none', cursor: 'pointer', fontSize: 12, color: 'var(--text2)', borderRadius: 4, flexShrink: 0 },
  orphelinHeader: { padding: '8px 14px', fontSize: 10, fontWeight: 700, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: 0.4, background: 'var(--bg)', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)' },
  recItemName: { fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 3 },
  recItemMeta: { fontSize: 11, color: 'var(--text2)' },
  rightCol: { display: 'flex', flexDirection: 'column', gap: 16, overflowY: 'auto', paddingRight: 4 },
  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: 40, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12 },
  actionBar: { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  ghostBtn: { padding: '7px 14px', background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text2)', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontFamily: 'var(--font)' },
  printZone: { display: 'flex', flexDirection: 'column', gap: 16, background: 'transparent' },
  header: { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: '18px 22px' },
  titleInput: { width: '100%', fontSize: 22, fontWeight: 700, color: 'var(--text)', fontFamily: 'var(--font-serif)', border: 'none', background: 'transparent', outline: 'none', padding: 0 },
  inlineField: { display: 'flex', flexDirection: 'column', gap: 3 },
  inlineInput: { padding: '5px 10px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 12, background: 'var(--bg)', fontFamily: 'var(--font)', color: 'var(--text)' },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 },
  card: { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden' },
  cardTitle: { padding: '12px 16px', borderBottom: '1px solid var(--border)', background: 'var(--bg)', fontSize: 12, fontWeight: 700, color: 'var(--text)', textTransform: 'uppercase', letterSpacing: 0.4 },
  paramGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: 12, padding: 14 },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 11, fontWeight: 600, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: 0.4 },
  input: { padding: '8px 12px', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', outline: 'none', boxSizing: 'border-box', width: '100%' },
  kpiGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, padding: 14 },
  kpiItem: { display: 'flex', flexDirection: 'column', gap: 4, padding: 10, background: 'var(--bg)', borderRadius: 8 },
  kpiLabel: { fontSize: 11, color: 'var(--text2)', fontWeight: 500 },
  smallBtn: { padding: '5px 12px', background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 6, fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
  ingHead: { display: 'grid', gridTemplateColumns: '2fr 80px 90px 110px 90px 32px', gap: 8, padding: '6px 0', borderBottom: '1px solid var(--border)', fontSize: 10, fontWeight: 700, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: 0.4 },
  ingRow: { display: 'grid', gridTemplateColumns: '2fr 80px 90px 110px 90px 32px', gap: 8, padding: '6px 0', alignItems: 'center' },
  ingInput: { padding: '6px 10px', border: '1px solid var(--border)', borderRadius: 6, fontSize: 12, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', outline: 'none', width: '100%', boxSizing: 'border-box' },
  scalingBar: { margin: '0 14px 8px', padding: '14px 16px', background: '#fefce8', border: '1px solid #fde68a', borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 8 },
  scalingBlock: { display: 'flex', flexDirection: 'column', gap: 4 },
  scalingBlockLabel: { fontSize: 10, fontWeight: 700, color: '#92400e', textTransform: 'uppercase', letterSpacing: 0.4 },
  suggestions: { position: 'absolute', top: '100%', left: 0, right: 0, background: 'var(--surface)', border: '1px solid var(--accent)', borderRadius: '0 0 8px 8px', zIndex: 50, boxShadow: '0 4px 16px rgba(0,0,0,0.15)', maxHeight: 200, overflowY: 'auto' },
  suggItem: { padding: '8px 12px', cursor: 'pointer', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 4 },
  // Version compacte (autocomplétion discrète)
  suggestionsCompact: { position: 'absolute', top: '100%', left: 0, right: 0, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 6, zIndex: 50, boxShadow: '0 2px 8px rgba(0,0,0,0.1)', maxHeight: 180, overflowY: 'auto', marginTop: 2 },
  suggItemCompact: { padding: '5px 10px', cursor: 'pointer', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', fontSize: 12, color: 'var(--text)' },
  deleteLineBtn: { width: 28, height: 28, border: '1px solid #fca5a5', background: 'none', color: '#dc2626', borderRadius: 6, cursor: 'pointer', fontSize: 13, padding: 0 },
  etapeRow: { display: 'flex', gap: 10, alignItems: 'flex-start', marginBottom: 10 },
  etapeNum: { width: 28, height: 28, borderRadius: '50%', background: 'var(--accent)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 2 },
  etapeInput: { flex: 1, padding: '8px 12px', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', outline: 'none', resize: 'vertical', lineHeight: 1.5 },
  moveBtn: { width: 22, height: 22, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text2)', borderRadius: 4, cursor: 'pointer', fontSize: 10, padding: 0 },
  textarea: { width: '100%', padding: '8px 12px', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', outline: 'none', resize: 'vertical', boxSizing: 'border-box', lineHeight: 1.5 },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modal: { background: 'var(--surface)', borderRadius: 14, width: 420, maxWidth: '90vw', boxShadow: '0 20px 60px rgba(0,0,0,0.2)' },
};

if (getBrowserWindow()?.innerWidth < 900) {
  cts.root = { ...cts.root, gridTemplateColumns: '1fr', height: 'auto' };
  cts.grid = { ...cts.grid, gridTemplateColumns: '1fr' };
}
