// Style de cellule CCNT (hors objet pls car utilisé dans table HTML native)
const ccntCell = {
  border: '1px solid #000',
  padding: '3px 5px',
  fontSize: 9,
  verticalAlign: 'middle',
};

const pls = {
  root: { display: 'flex', flexDirection: 'column', gap: 14 },
  tabs: { display: 'flex', gap: 4, alignItems: 'center', flexWrap: 'wrap' },
  tab: { padding: '8px 16px', border: '1px solid var(--border)', borderRadius: 8, background: 'var(--surface)', color: 'var(--text2)', fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: 'var(--font)' },
  tabActive: { background: 'var(--nav)', color: '#fff', borderColor: 'var(--nav)' },
  actionsBar: { display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  addBtn: { padding: '9px 16px', background: 'var(--accent)', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
  exportBtn: { padding: '8px 14px', background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text2)', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontFamily: 'var(--font)' },
  ghostBtn: { padding: '8px 14px', background: 'none', border: '1px solid var(--border)', color: 'var(--text2)', borderRadius: 8, fontSize: 12, cursor: 'pointer', fontFamily: 'var(--font)' },
  pointBtn: { padding: '10px 16px', background: 'var(--success-text)', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)', flex: 1 },
  datePicker: { padding: '8px 12px', border: '1px solid var(--border)', borderRadius: 8, background: 'var(--surface)', fontFamily: 'var(--font)', fontSize: 13 },
  smallBtn: { padding: '7px 10px', border: '1px solid var(--border)', background: 'var(--surface)', borderRadius: 8, fontSize: 12, cursor: 'pointer' },
  smallBtnActive: { background: 'var(--accent-light)', color: 'var(--accent)', borderColor: 'var(--accent)' },
  card: { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: 16 },
  grid: { display: 'grid', gap: 0 },
  empColHeader: { height: 48, borderBottom: '1px solid var(--border)', background: 'var(--bg)' },
  dayHeader: { height: 48, borderBottom: '1px solid var(--border)', borderLeft: '1px solid var(--border)', background: 'var(--bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 4 },
  empCol: { display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', borderBottom: '1px solid var(--border)', background: 'var(--bg)', position: 'sticky', left: 0, zIndex: 1 },
  empAvatar: { width: 30, height: 30, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: 11, flexShrink: 0 },
  empName: { fontSize: 12, fontWeight: 600 },
  dayCell: { minHeight: 72, padding: 6, borderLeft: '1px solid var(--border)', borderBottom: '1px solid var(--border)' },
  shiftCell: { borderRadius: 8, padding: '8px 6px', position: 'relative', border: '1px solid var(--border)' },
  emptyCell: { height: '100%', minHeight: 58, border: '1px dashed var(--border)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  addHint: { fontSize: 18, color: 'var(--text2)' },
  ptTable: { display: 'flex', flexDirection: 'column' },
  ptHead: { display: 'grid', gridTemplateColumns: '1.5fr 1fr 1fr 1fr 1fr 1fr', padding: '8px 16px', background: 'var(--bg)', fontSize: 10, fontWeight: 700, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: 0.4, borderBottom: '1px solid var(--border)' },
  ptRow: { display: 'grid', gridTemplateColumns: '1.5fr 1fr 1fr 1fr 1fr 1fr', padding: '12px 16px', borderBottom: '1px solid var(--border)', alignItems: 'center', cursor: 'pointer' },
  ptEmp: { display: 'flex', alignItems: 'center', gap: 10 },
  ptAvatar: { width: 30, height: 30, borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: 10 },
  ptName: { fontSize: 13, fontWeight: 600 },
  ptCell: { fontSize: 13 },
  statusBadge: { display: 'inline-block', padding: '3px 9px', borderRadius: 12, fontSize: 11, fontWeight: 600 },

  // Mobile
  mobilePlanList: { display: 'flex', flexDirection: 'column', gap: 10 },
  mobileTitle: { fontSize: 15, fontWeight: 700, fontFamily: 'var(--font-serif)', padding: '4px 0' },
  mobileDayBlock: { background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, overflow: 'hidden' },
  mobileDayHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', background: 'var(--bg)', borderBottom: '1px solid var(--border)' },
  mobileDayAdd: { width: 26, height: 26, borderRadius: 6, background: 'var(--accent)', color: '#fff', border: 'none', fontSize: 15, cursor: 'pointer', fontFamily: 'var(--font)' },
  mobileShiftCard: { display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderBottom: '1px solid var(--border)', cursor: 'pointer' },
  mobileBadge: { fontSize: 10, fontWeight: 600, padding: '3px 8px', borderRadius: 10, whiteSpace: 'nowrap' },

  // Mobile - vue agenda par jour (refonte lisibilité)
  mobilePlanWrap: { display: 'flex', flexDirection: 'column' },
  mobileDayNav: { position: 'sticky', top: 0, zIndex: 5, display: 'flex', flexDirection: 'column', gap: 8, padding: '6px 0 10px', marginBottom: 6, background: 'var(--bg)', borderBottom: '1px solid var(--border)' },
  mobileDayNavRow: { display: 'flex', alignItems: 'center', gap: 8 },
  mobileNavArrow: { width: 44, height: 44, flexShrink: 0, borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', fontSize: 22, lineHeight: 1, cursor: 'pointer', fontFamily: 'var(--font)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  mobileDayNavCenter: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 3, textAlign: 'center', overflow: 'hidden' },
  mobileDayName: { fontSize: 16, fontWeight: 700, fontFamily: 'var(--font-serif)', maxWidth: '100%', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', textTransform: 'capitalize' },
  mobileTodayChip: { fontSize: 10, fontWeight: 700, color: 'var(--accent)', background: 'var(--accent-light)', padding: '1px 8px', borderRadius: 10, textTransform: 'uppercase', letterSpacing: 0.4 },
  mobileTodayBtn: { width: '100%', minHeight: 44, borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--accent)', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },
  mobileCoverage: { fontSize: 12, fontWeight: 600, color: 'var(--text2)', padding: '2px 2px 4px' },
  mobileCard: { position: 'relative', display: 'flex', alignItems: 'stretch', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, overflow: 'hidden', cursor: 'pointer', minHeight: 44 },
  mobileCardSelected: { borderColor: 'var(--accent)', background: 'var(--accent-light)' },
  mobileCardBand: { width: 5, flexShrink: 0 },
  mobileCardBody: { flex: 1, minWidth: 0, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 4 },
  mobileCardTop: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  mobileHour: { fontSize: 20, fontWeight: 800, color: 'var(--text)', letterSpacing: 0.3, fontFamily: 'var(--font)' },
  mobileCheckbox: { width: 22, height: 22, flexShrink: 0 },
  mobileStatus: { fontSize: 10, fontWeight: 700, padding: '3px 9px', borderRadius: 10, whiteSpace: 'nowrap', flexShrink: 0 },
  mobileName: { fontSize: 14, fontWeight: 600, color: 'var(--text)' },
  mobileMeta: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginTop: 2 },
  mobileChip: { fontSize: 11, fontWeight: 600, padding: '2px 9px', borderRadius: 20, border: '1px solid', background: 'transparent', whiteSpace: 'nowrap' },
  mobilePause: { fontSize: 11, color: 'var(--text3)', fontWeight: 400 },
  mobileEmptyDay: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: '32px 16px', background: 'var(--surface)', border: '1px dashed var(--border)', borderRadius: 12 },
  mobileAddRow: { width: '100%', minHeight: 44, padding: '11px 14px', background: 'var(--surface)', border: '1px dashed var(--border)', borderRadius: 12, color: 'var(--accent)', fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)' },

  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: 12 },
  modal: { background: 'var(--surface)', borderRadius: 14, width: 480, maxWidth: '100%', maxHeight: '90vh', overflowY: 'auto', boxShadow: '0 20px 60px rgba(0,0,0,0.2)' },
  modalHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 20px', borderBottom: '1px solid var(--border)' },
  modalTitle: { fontWeight: 700, fontSize: 16, fontFamily: 'var(--font-serif)' },
  closeBtn: { background: 'none', border: 'none', fontSize: 18, cursor: 'pointer', color: 'var(--text2)' },
  fieldLabel: { display: 'block', fontSize: 11, fontWeight: 600, color: 'var(--text2)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.4 },
  fieldInput: { width: '100%', padding: '9px 12px', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--text)', background: 'var(--bg)', fontFamily: 'var(--font)', boxSizing: 'border-box' },

  // Navigation temporelle du header (Refonte UI/UX)
  weekNav: { display: 'flex', alignItems: 'center', gap: 4 },
  navArrow: { width: 34, height: 34, borderRadius: 8, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--text)', fontSize: 18, lineHeight: 1, cursor: 'pointer', fontFamily: 'var(--font)', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  weekLabel: { fontSize: 13, fontWeight: 600, color: 'var(--text)', minWidth: 130, textAlign: 'center', textTransform: 'capitalize' },

  // Menu overflow ⋯
  overflowBackdrop: { position: 'fixed', inset: 0, zIndex: 40 },
  overflowMenu: { position: 'absolute', right: 0, top: 'calc(100% + 6px)', zIndex: 50, minWidth: 200, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, boxShadow: '0 12px 32px rgba(0,0,0,0.16)', padding: 6, display: 'flex', flexDirection: 'column', gap: 2 },
  overflowItem: { textAlign: 'left', padding: '10px 12px', background: 'none', border: 'none', borderRadius: 6, fontSize: 13, color: 'var(--text)', cursor: 'pointer', fontFamily: 'var(--font)', minHeight: 40 },

  // Barre d'action sticky pour la sélection multiple (Axe 2)
  selectionBar: { position: 'fixed', left: 0, right: 0, bottom: 0, zIndex: 1100, display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px', background: 'var(--surface)', borderTop: '1px solid var(--border)', boxShadow: '0 -6px 24px rgba(0,0,0,0.12)', flexWrap: 'wrap' },
  selectionCount: { fontSize: 13, fontWeight: 700, color: 'var(--text)' },
  selectionGhostBtn: { padding: '10px 14px', background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text2)', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font)', minHeight: 44 },
  selectionDeleteBtn: { padding: '10px 16px', background: 'var(--danger-strong)', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: 'pointer', fontFamily: 'var(--font)', minHeight: 44 },
};

export { ccntCell, pls };
